### ISSUE TITLE
SV-cosface不收敛

### ISSUE THREAD

**Issue by icodingc** [xiaoboCASIA/SV-X-Softmax#1]
你好，我实现了一下SV-cosface，但是调节t的时候发现t越大越难收敛效果越差，而且没有t=1时候效果好。其他参数设置都是一样的，请问你们这个SV系列调参有什么策略么？

**Comment by xiaoboCASIA** [comment]
@icodingc , 你好！ 请问下你的训练数据是？t越大确实难收敛，甚至可能不收敛（如t=1.4）。效果上我们暂时一直用t=1.2

**Comment by icodingc** [comment]
用的不是公开的人脸数据集，但也是10w id量级的数据。先前用的margin based softmax效果还不错。

**Comment by twmht** [comment]
@icodingc 

我測試的效果的確都是 t=1 的時候比較好，你有測試過 t>1 的時候情況有變好嗎？

**Comment by icodingc** [comment]
没有 ，逐渐变差。

**Comment by twmht** [comment]
@icodingc 

你覺得可能是數據集的關係嗎？

我還沒有試 MS1M，我用的是 private data。
